modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/CrimsonDawn45/survival-additions/issues" #optional

[[mods]] #mandatory
modId="cdsam" #mandatory
version="1.0.0" #mandatory
displayName="Survival Additions" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/survival-additions" #optional
logoFile="cdsam.png" #optional
authors="CrimsonDawn45" #optional
description='''
adds new tools and food items for extreme survival situations and makes a few previously uncraftable items craftable
'''
[[dependencies.cdsam]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.cdsam]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
